name: Proposal
description: Suggest an addition or modification to the existing spec
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize your proposal in a few sentences.
    validations:
      required: true
  - type: dropdown
    id: versions
    attributes:
      label: Version
      description: What version(s) of the spec are you using?
      multiple: true
      options:
        - First Editor’s Draft
        - Second Editor’s Draft
        - Third Editor’s Draft
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem & motivation
      description: In detail, what are the problem(s) you’re attempting to solve, either in your own design system or with the current specification syntax? List specific examples of how the current syntax doesn’t meet your needs.
    validations:
      required: true
  - type: textarea
    id: syntax
    attributes:
      label: Syntax
      description: Describe the proposed syntax, in JSON format
      render: json
    validations:
      required: true
  - type: textarea
    id: prior_art
    attributes:
      label: Prior art
      description: List prior art—any relevant technical specifications, books, blog posts, conference talks from experts on the subject.
    validations:
      required: true
  - type: textarea
    id: pros_cons
    attributes:
      label: Pros & cons
      description: What are the pros and cons of the change? If this is a backwards compatible change, list it as a “pro,” otherwise, list it as a “con.”
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What are alternate proposals that may address the same problem? If this is not backwards compatible, what could a backwards compatible version look like? For each, describe why it’s not considered.
    validations:
      required: true
  - type: checkboxes
    id: required_checks
    attributes:
      label: Required
      options:
        - label: I have searched [existing issues](https://github.com/design-tokens/community-group/issues) and there is not already an open issue on the subject.
          required: true
        - label: I have read and agree to abide by the [CODE_OF_CONDUCT](https://github.com/design-tokens/community-group/blob/CODE_OF_CONDUCT.md)
          required: true
