name: Pull request CI
on: [pull_request]

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
  # See https://github.com/w3c/respec/pull/3306
  LC_ALL: en_US.UTF-8
  FORCE_COLOR: 1

jobs:
  lint:
    name: Check linting issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run lint
