name: Pull request CI
on: [pull_request]

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
  # See https://github.com/w3c/respec/pull/3306
  LC_ALL: en_US.UTF-8
  FORCE_COLOR: 1

jobs:
  lint:
    name: Check linting issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: pnpm run lint
